openapi: 3.0.0
info:
  title: parameters
  version: '1.0'
  description: 'El presente muesta los servicios web (web services) de tipo REST, que están implementados en el sistema de hostal, es importante considerar que la documentación mostrada aqui es para uso interno.'
  contact:
    name: Hans Villaizan
    url: zolymo.blogspot.com
    email: zolymo@cgmail.om
  license:
    name: Apache 2.0
servers:
  - url: 'http://35.247.212.153:8081/parameters'
paths:
  /v1/company/corporate:
    get:
      summary: Lista Corporate
      tags:
        - company
      operationId: getCorporate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/companyvo.v1.yaml
              examples:
                lista corporativo:
                  value:
                    createdBy: INITIALCFG
                    createdAt: '05/09/2019 18:43:58'
                    updatedBy: INITIALCFG
                    updatedAt: '05/09/2019 18:43:58'
                    deletedBy: null
                    deletedAt: null
                    activeRow: true
                    nit: XXXXXXXXXXXC
                    name: INOVASTUDIO GROUP SAC
                    commercialName: INOVASTUDIO
                    slogan: Todo nace con una idea
                    abbreviation: AAA
                    idCompany: iNovaStudio
                    contactPeople: Hans Yamamoto
                    logoPath: null
                    idkey: AAA
                    generatedUidc: true
                    masterCompany: '-'
                    organizationType: CORPORATIVO
                    personeryType: JURIDICA
                    companyType: HOSTAL
                    nitType: RUC
                    stakeholderType: CLIENTE_INTERNO
                    userAudit: null
      description: RCorp
      parameters: []
  /v1/company/corporate/inactive:
    get:
      summary: Lista Corporate Inactivo
      tags:
        - company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/companyvo.v1.yaml
      description: RCorpInactivo
      operationId: getCorporateInactive
  /v1/company:
    get:
      summary: Lista Branch
      tags:
        - company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/companyvo.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/userauditvo.v1.yaml
            examples:
              usuarioLogueado:
                value:
                  loginname: ZOLYMO
                  corporate: BAA
                  branch: BAX
      description: RBranch
      operationId: getBranch
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            default: '35.247.212.153:8081'
          in: header
          name: Host
          required: true
    parameters: []
    post:
      summary: Crea Branch
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../common/models/operationresult.v1.yaml
              examples:
                corporativoCreado:
                  value:
                    codigo: '0000'
                    descripcion: Satisfactorio
                    codigobackend: null
      description: Crea Sucursal
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/companyvo.v1.yaml
            examples:
              creaCorporativo:
                value:
                  createdBy: null
                  createdAt: null
                  updatedBy: null
                  updatedAt: null
                  deletedBy: null
                  deletedAt: null
                  activeRow: null
                  nit: '10702433924'
                  name: Corporacion CAA
                  commercialName: ''
                  slogan: ''
                  abbreviation: CAA
                  idCompany: Corporacion CAA
                  contactPeople: HansVillaizan Cel 982581458
                  logoPath: null
                  idKey: null
                  generatedUidc: true
                  masterCompany: null
                  organizationType: CORPORATIVO
                  personeryType: JURIDICA
                  companyType: HOSTAL
                  nitType: RUC
                  stakeholderType: CLIENTE_INTERNO
                  userAudit:
                    loginname: ZOLYTO
                    corporate: AAA
                    branch: BAX
              creaBranch:
                value:
                  createdBy: null
                  createdAt: null
                  updatedBy: null
                  updatedAt: null
                  deletedBy: null
                  deletedAt: null
                  activeRow: null
                  nit: '10702433924'
                  name: Hostal Novo
                  commercialName: ''
                  slogan: ''
                  abbreviation: CAX
                  idCompany: Hostal Novo
                  contactPeople: Hans Villaizan Cel 982581458
                  logoPath: null
                  idKey: null
                  generatedUidc: true
                  masterCompany: null
                  organizationType: SUCURSAL
                  personeryType: JURIDICA
                  companyType: HOSTAL
                  nitType: RUC
                  stakeholderType: CLIENTE_INTERNO
                  userAudit:
                    loginname: ZOLYTO
                    corporate: CAA
                    branch: '-'
      tags:
        - company
      operationId: creaBranch
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
components:
  schemas: {}
